name: Deploy Sniper Signal Bot to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Log in to Heroku
      uses: akshnz/heroku-cli-action@v1.0
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/YOUR-APP-NAME.git
        git push heroku main
